version: '3.8'
services:

    vsc-server:
        build: .
        container_name: app-vsc-server
        volumes:
            - ${HOME}/.config/code-server/config.yaml:/home/coder/.config/code-server/config.yaml
            - ${HOME}/.m2/repository:/home/coder/.m2/repository
            - ${HOME}/.m2/settings.xml:/home/coder/.m2/settings.xml
            - ${HOME}/.gitconfig:/home/coder/.gitconfig
            - ${PWD}/..:/home/coder/project
        environment:
            - DOCKER_USER=$USER
            - PORT=40000
        network_mode: host
        user: "${EXAMPLE_UID}:${EXAMPLE_GID}"
