version: '3.8'
services:

    vsc-server:
        build: .
        container_name: code-server
        hostname: code-server
        networks:
            vsc-net:
        volumes:
            - /home/robert/.config/code-server/config.yaml:/home/coder/.config/code-server/config.yaml
            - /home/robert/.m2/repository:/home/coder/.m2/repository
            - ${PWD}/..:/home/coder/project
        environment:
            - DOCKER_USER=$USER
            - PORT=40000
        user: "${EXAMPLE_UID}:${EXAMPLE_GID}"
        expose:
            - 40000
            - 40001
        ports:        
            - 40000:40000
            - 40001:40001

networks:
    vsc-net:
