version: '3.8'
services:

    vsc-server:
        build: .
        container_name: app-vsc-server
        volumes:
            - /home/robert/.config/code-server/config.yaml:/home/coder/.config/code-server/config.yaml
            - /home/robert/.m2/repository:/home/coder/.m2/repository
            - /home/robert/.m2/settings.xml:/home/coder/.m2/settings.xml
            - ${PWD}/..:/home/coder/project
        environment:
            - DOCKER_USER=$USER
            - PORT=40000
        network: host
        user: "${EXAMPLE_UID}:${EXAMPLE_GID}"
